import React, { useState } from 'react';
import { Archive } from 'lucide-react';
import JSZip from 'jszip';
import Card from '../ui/Card';
import Badge from '../ui/Badge';
import Button from '../ui/Button';
import { generateCSV, getQuarter } from '../../lib/utils';

const Reports = ({ invoices, expenses, userSettings, addToast }) => {
  const [periodType, setPeriodType] = useState(userSettings.filingFrequency || 'Monthly'); 
  const [selectedMonth, setSelectedMonth] = useState(new Date().toISOString().slice(0, 7)); 
  const [selectedQuarter, setSelectedQuarter] = useState('Q3 (Oct-Dec)');
  const [isZipping, setIsZipping] = useState(false);

  // Filter Data
  const filteredInvoices = invoices.filter(inv => {
    if (!inv.date) return false;
    if (periodType === 'Monthly') return inv.date.startsWith(selectedMonth);
    return getQuarter(inv.date) === selectedQuarter; 
  });

  const filteredExpenses = expenses.filter(exp => {
    if (!exp.date) return false;
    if (periodType === 'Monthly') return exp.date.startsWith(selectedMonth);
    return getQuarter(exp.date) === selectedQuarter;
  });

  // Calculations
  const totalLiability = filteredInvoices.reduce((acc, i) => acc + (parseFloat(i.tax) || 0), 0);
  const eligibleItc = filteredExpenses.reduce((acc, i) => acc + (parseFloat(i.gst_paid) || 0), 0);
  const netPayable = Math.max(0, totalLiability - eligibleItc);

  const handleDownloadZip = async () => {
    setIsZipping(true);
    addToast("Preparing CA Filing Bundle...", "info");
    try {
      const zip = new JSZip();

      // 1. GSTR-1 JSON (Mock Structure for example)
      const gstr1Data = {
        gstin: userSettings.gstin,
        fp: periodType === 'Monthly' ? selectedMonth.replace('-', '') : selectedQuarter,
        b2b: filteredInvoices.map(inv => ({ 
            ctin: inv.client?.gstin || "", 
            inv: [{ inum: inv.id, idt: inv.date, val: inv.amount }] 
        })),
      };
      zip.file("GSTR1_Report.json", JSON.stringify(gstr1Data, null, 2));

      // 2. CSV Summaries
      const safeClientName = (client) => typeof client === 'object' && client !== null ? client.name : client;

      zip.file("Sales_Register.csv", generateCSV(filteredInvoices.map(i => ({
        ID: i.id, 
        Date: i.date, 
        Client: safeClientName(i.client), 
        Tax: i.tax, 
        Total: i.amount
      }))));
      
      zip.file("Expense_Register.csv", generateCSV(filteredExpenses.map(e => ({
          ID: e.id, 
          Date: e.date, 
          Category: e.category, 
          Amount: e.amount, 
          ITC: e.gst_paid
      }))));

      // 3. CA Instruction Note
      const summaryText = `
        GST Filing Summary
        ------------------
        Period: ${periodType === 'Monthly' ? selectedMonth : selectedQuarter}
        Company: ${userSettings.companyName}
        GSTIN: ${userSettings.gstin}
        
        Total Outward Liability: ₹${totalLiability}
        Total Input Tax Credit: ₹${eligibleItc}
        Net Payable (Cash Ledger): ₹${netPayable}
        
        Generated by InvoicerInd
      `;
      zip.file("Summary_Note.txt", summaryText);

      // 4. Expense Receipts Folder
      const receiptsFolder = zip.folder("Expense_Receipts");
      filteredExpenses.forEach(exp => {
        if (exp.receipt_data) {
            // Remove Data URL prefix
            const base64Data = exp.receipt_data.split(',')[1]; 
            if (base64Data) {
                const fileName = `${exp.id}_${exp.receipt_name || 'receipt.jpg'}`;
                receiptsFolder.file(fileName, base64Data, {base64: true});
            }
        }
      });

      // Generate Zip
      const content = await zip.generateAsync({type:"blob"});
      const url = URL.createObjectURL(content);
      const a = document.createElement('a');
      a.href = url;
      a.download = `GST_Filing_${userSettings.companyName}_${periodType === 'Monthly' ? selectedMonth : selectedQuarter}.zip`;
      a.click();
      URL.revokeObjectURL(url);
      addToast("Filing bundle downloaded successfully!", "success");

    } catch (e) {
      console.error("ZIP Generation failed", e);
      addToast("Failed to generate ZIP.", "error");
    } finally {
      setIsZipping(false);
    }
  };

  return (
    <div className="space-y-6">
       <div className="flex flex-col md:flex-row justify-between items-end gap-4">
         <div>
           <h2 className="text-2xl font-bold dark:text-white">Tax Reports & Filing</h2>
           <p className="text-slate-500 text-sm">Consolidated data for your Chartered Accountant</p>
         </div>
         
         <div className="flex gap-2 items-center bg-white dark:bg-slate-800 p-2 rounded-lg border border-slate-200 dark:border-slate-700">
            <div className="flex rounded-md bg-slate-100 dark:bg-slate-700 p-1">
              <button onClick={() => setPeriodType('Monthly')} className={`px-3 py-1 text-xs font-medium rounded ${periodType === 'Monthly' ? 'bg-white shadow text-slate-900' : 'text-slate-500'}`}>Monthly</button>
              <button onClick={() => setPeriodType('Quarterly')} className={`px-3 py-1 text-xs font-medium rounded ${periodType === 'Quarterly' ? 'bg-white shadow text-slate-900' : 'text-slate-500'}`}>Quarterly</button>
            </div>
            
            {periodType === 'Monthly' ? (
               <input type="month" value={selectedMonth} onChange={(e) => setSelectedMonth(e.target.value)} className="bg-transparent border-none text-sm focus:ring-0" />
            ) : (
               <select value={selectedQuarter} onChange={(e) => setSelectedQuarter(e.target.value)} className="bg-transparent border-none text-sm focus:ring-0">
                 <option>Q1 (Apr-Jun)</option>
                 <option>Q2 (Jul-Sep)</option>
                 <option>Q3 (Oct-Dec)</option>
                 <option>Q4 (Jan-Mar)</option>
               </select>
            )}
         </div>
       </div>

       <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <Card className="p-6">
            <div className="flex justify-between items-center mb-6">
              <h3 className="font-bold text-slate-800 dark:text-white">Summary of Outward Supplies</h3>
              <Badge type="primary">{filteredInvoices.length} Invoices</Badge>
            </div>
            <div className="space-y-4">
              <div className="flex justify-between p-3 bg-slate-50 dark:bg-slate-800 rounded">
                <span className="text-sm text-slate-600 dark:text-slate-400">Total Liability (Tax Collected)</span>
                <span className="font-semibold dark:text-white">₹{totalLiability.toLocaleString()}</span>
              </div>
              <div className="pt-2 border-t dark:border-slate-700 flex justify-between">
                 <span className="font-bold text-slate-800 dark:text-white">Net Tax Liability</span>
                 <span className="font-bold text-slate-800 dark:text-white">₹{totalLiability.toLocaleString()}</span>
              </div>
            </div>
          </Card>

          <Card className="p-6">
            <div className="flex justify-between items-center mb-6">
              <h3 className="font-bold text-slate-800 dark:text-white">Input Tax Credit</h3>
              <Badge type="warning">{filteredExpenses.length} Expenses</Badge>
            </div>
             <div className="space-y-4">
              <div className="flex justify-between p-3 bg-slate-50 dark:bg-slate-800 rounded">
                <span className="text-sm text-slate-600 dark:text-slate-400">Eligible ITC (From Expenses)</span>
                <span className="font-semibold dark:text-white">₹{eligibleItc.toLocaleString()}</span>
              </div>
              <div className="pt-2 border-t dark:border-slate-700 flex justify-between">
                 <span className="font-bold text-slate-800 dark:text-white">Net Payable in Cash</span>
                 <span className={`font-bold ${netPayable > 0 ? 'text-red-600' : 'text-emerald-600'}`}>
                   ₹{netPayable.toLocaleString()}
                 </span>
              </div>
            </div>
          </Card>
       </div>
       
       <Card className="p-8 bg-gradient-to-br from-slate-800 to-slate-900 text-white flex flex-col md:flex-row items-center justify-between gap-6">
         <div>
           <h3 className="text-xl font-bold flex items-center gap-2"><Archive size={24} className="text-emerald-400"/> CA Filing Bundle</h3>
           <p className="text-slate-400 text-sm mt-2 max-w-md">
             Download a consolidated ZIP file containing the GSTR-1 JSON, Sales Register (CSV), Expense Register (CSV), receipts, and a summary note.
           </p>
         </div>
         <Button onClick={handleDownloadZip} loading={isZipping} className="bg-emerald-500 hover:bg-emerald-600 text-white px-8 py-3 h-12">
           {isZipping ? "Generating ZIP..." : "Download CA Bundle (.zip)"}
         </Button>
       </Card>
    </div>
  )
}

export default Reports;